"""initial_migration

Revision ID: 14ca4942a091
Revises: 
Create Date: 2025-11-03 18:00:17.664990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ca4942a091'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_tags_tag_id'), table_name='file_tags')
    op.create_index('ix_file_tags_tag_id_file_hash', 'file_tags', ['tag_id', 'file_sha256_hash'], unique=False)
    op.add_column('files', sa.Column('ai_generated', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'ai_generated')
    op.drop_index('ix_file_tags_tag_id_file_hash', table_name='file_tags')
    op.create_index(op.f('ix_file_tags_tag_id'), 'file_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###
