"""update models

Revision ID: 845fea78af1d
Revises: 2238095eda3b
Create Date: 2025-11-25 19:37:21.504339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845fea78af1d'
down_revision: Union[str, Sequence[str], None] = '2238095eda3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('SERIES', 'COLLECTION', name='poolcategory'), server_default='SERIES', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pool_members',
    sa.Column('pool_id', sa.Uuid(), nullable=False),
    sa.Column('file_sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_sha256_hash'], ['files.sha256_hash'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pool_id', 'file_sha256_hash')
    )
    op.create_index('ix_pool_members_file_hash', 'pool_members', ['file_sha256_hash'], unique=False)
    op.create_index('ix_pool_members_pool_order', 'pool_members', ['pool_id', 'order'], unique=False)
    op.drop_constraint(op.f('file_tags_file_sha256_hash_fkey'), 'file_tags', type_='foreignkey')
    op.drop_constraint(op.f('file_tags_tag_id_fkey'), 'file_tags', type_='foreignkey')
    op.create_foreign_key(None, 'file_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'file_tags', 'files', ['file_sha256_hash'], ['sha256_hash'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file_tags', type_='foreignkey')
    op.drop_constraint(None, 'file_tags', type_='foreignkey')
    op.create_foreign_key(op.f('file_tags_tag_id_fkey'), 'file_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('file_tags_file_sha256_hash_fkey'), 'file_tags', 'files', ['file_sha256_hash'], ['sha256_hash'])
    op.drop_index('ix_pool_members_pool_order', table_name='pool_members')
    op.drop_index('ix_pool_members_file_hash', table_name='pool_members')
    op.drop_table('pool_members')
    op.drop_table('pools')
    # ### end Alembic commands ###
