"""add phash column for visual similarity

Revision ID: a1512bd0b340
Revises: deb2fc83c86d
Create Date: 2026-01-01 11:57:21.843217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1512bd0b340'
down_revision: Union[str, Sequence[str], None] = 'deb2fc83c86d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('phash', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_files_phash'), 'files', ['phash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_phash'), table_name='files')
    op.drop_column('files', 'phash')
    # ### end Alembic commands ###
