"""initial_schema_with_tag_source

Revision ID: a75ccee16d61
Revises: 
Create Date: 2025-11-11 18:34:27.293253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75ccee16d61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('md5_hash', sa.String(length=32), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_ext', sa.String(length=20), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Enum('SAFE', 'SENSITIVE', 'QUESTIONABLE', 'EXPLICIT', name='rating'), server_default='EXPLICIT', nullable=False),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=2048), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tag_source', sa.Enum('DANBOORU', 'ONNX', name='tagsource'), server_default='ONNX', nullable=False),
    sa.PrimaryKeyConstraint('sha256_hash')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('GENERAL', 'ARTIST', 'COPYRIGHT', 'CHARACTER', 'META', name='tagcategory'), server_default='GENERAL', nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('file_tags',
    sa.Column('file_sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_sha256_hash'], ['files.sha256_hash'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('file_sha256_hash', 'tag_id')
    )
    op.create_index('ix_file_tags_file_sha256_hash', 'file_tags', ['file_sha256_hash'], unique=False)
    op.create_index('ix_file_tags_tag_id_file_hash', 'file_tags', ['tag_id', 'file_sha256_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_tags_tag_id_file_hash', table_name='file_tags')
    op.drop_index('ix_file_tags_file_sha256_hash', table_name='file_tags')
    op.drop_table('file_tags')
    op.drop_table('tags')
    op.drop_table('files')
    # ### end Alembic commands ###
