"""sync models

Revision ID: deb2fc83c86d
Revises: 845fea78af1d
Create Date: 2025-12-25 21:01:49.724013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb2fc83c86d'
down_revision: Union[str, Sequence[str], None] = '845fea78af1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_families',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_sha256_hash'], ['files.sha256_hash'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_sha256_hash')
    )
    op.add_column('files', sa.Column('parent_family_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'files', 'file_families', ['parent_family_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'parent_family_id')
    op.drop_table('file_families')
    # ### end Alembic commands ###
